# PROPRIETARY AND CONFIDENTIAL
# Copyright (c) 2026 Guillaume Lessard / qector-decoder-v3
# All Rights Reserved. NDA evaluation only. Do not redistribute.
from __future__ import annotations
from typing import Literal, Sequence
import numpy as np
import numpy.typing as npt

_U8 = npt.NDArray[np.uint8]
_F64 = npt.NDArray[np.float64]

DECODER_VERSION: str
TARGET_HARDWARE: str
TARGET_ARCHITECTURE: str
__version__: str

class IonQSuperionDecoder:
    def __init__(self, code: str = ..., error_rate: float = ...) -> None: ...
    @staticmethod
    def q102(error_rate: float = ...) -> IonQSuperionDecoder: ...
    @staticmethod
    def gross(error_rate: float = ...) -> IonQSuperionDecoder: ...
    @staticmethod
    def q70(error_rate: float = ...) -> IonQSuperionDecoder: ...
    @staticmethod
    def from_checks(check_to_qubits: Sequence[Sequence[int]], n_qubits: int | None = ..., error_rate: float = ..., name: str = ...) -> IonQSuperionDecoder: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def decode_with_erasures(self, syndrome: _U8, erasures: _U8) -> _U8: ...
    def decode_batch_flat(self, syndromes: _U8, batch_size: int) -> _U8: ...
    def update(self, round_syndrome: _U8) -> _U8: ...
    def set_uniform_schedule(self, p: float) -> None: ...
    def set_schedule(self, p_meas: Sequence[float], p_data: Sequence[float], label: str) -> None: ...
    def set_qubit_priors(self, p_data: _F64) -> None: ...
    def set_strict_verify(self, on: bool) -> None: ...
    def flush(self) -> None: ...
    def backend(self) -> str: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...
    @property
    def history_len(self) -> int: ...
    @property
    def schedule_label(self) -> str: ...
    @property
    def code_name(self) -> str: ...
    @property
    def artifact_hash(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def target_hardware(self) -> str: ...
    @property
    def check_to_qubits(self) -> list[list[int]]: ...

class BPOSDDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: int | None, error_rate: float, bp_method: Literal["exact", "min_sum"] | None = ..., osd_order: int | None = ...) -> None: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    def batch_decode(self, syndromes: npt.NDArray[np.uint8]) -> npt.NDArray[np.uint8]: ...
    def decode_timed(self, syndrome: _U8, max_latency_ms: float) -> _U8: ...
    def bp_decode(self, syndrome: _U8, max_iterations: int) -> _F64: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class TwoStageDecoder:
    @staticmethod
    def from_checks(check_to_qubits: Sequence[Sequence[int]], n_qubits: int | None = ..., error_rate: float = ...) -> TwoStageDecoder: ...
    @staticmethod
    def q102(error_rate: float = ...) -> TwoStageDecoder: ...
    @staticmethod
    def q70(error_rate: float = ...) -> TwoStageDecoder: ...
    @staticmethod
    def gross(error_rate: float = ...) -> TwoStageDecoder: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

class SpaceTimeDecoder:
    def __init__(self, check_to_qubits: Sequence[Sequence[int]], n_qubits: int | None = ..., rounds: int = ..., error_rate: float = ...) -> None: ...
    def decode_rounds_flat(self, flat_syndromes: _U8, rounds: int) -> _U8: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...
    @property
    def rounds(self) -> int: ...

class AutoDecoder:
    def __init__(self, code: str = ..., error_rate: float = ..., priority: Literal["accuracy", "speed", "balanced"] = ...) -> None: ...
    @staticmethod
    def recommend(code: str, priority: str) -> str: ...
    def decode(self, syndrome: _U8) -> _U8: ...
    @property
    def backend(self) -> str: ...
    @property
    def priority(self) -> str: ...
    @property
    def is_hyperedge(self) -> bool: ...
    @property
    def n_qubits(self) -> int: ...
    @property
    def n_checks(self) -> int: ...

def py_license_status() -> tuple[str, bool, str]: ...
def py_latency_stats() -> tuple[int, float, float, float, float]: ...
def py_latency_stats_scoped(scope: str) -> tuple[int, float, float, float, float]: ...
def py_latency_scopes() -> list[str]: ...
def py_reset_latency() -> None: ...
